This should now fail...

diff --git a/.github/workflows/self_hosted_tests.yml b/.github/workflows/self_hosted_tests.yml
--- a/.github/workflows/self_hosted_tests.yml
+++ b/.github/workflows/self_hosted_tests.yml
@@ -427,14 +427,14 @@ jobs:
         source pyenv/bin/activate
         python -m spinnaker_testbase.test_no_job_destroy
 
-    # - name: Fail if any step failed
-    #  if: failure()
-    #  shell: bash
-    #  env:
-    #    STEPS_CONTEXT: ${{ toJson(steps) }}
-    #  run: |
-    #    echo "$STEPS_CONTEXT" | jq -r 'keys[] as $k | select(.[$k].outcome=="failure") | "\($k): \(.[$k].outcome)"'
-    #    exit 1
+    - name: Fail if any step failed
+      if: failure()
+      shell: bash
+      env:
+        STEPS_CONTEXT: ${{ toJson(steps) }}
+      run: |
+        echo "$STEPS_CONTEXT" | jq -r 'keys[] as $k | select(.[$k].outcome=="failure") | "\($k): \(.[$k].outcome)"'
+        exit 1
 
     - name: Extract branch name
       shell: bash
